mxzpcg_characters:
    resource: "@MXZPCGBundle/Resources/config/routing/characters.yml"
    prefix:   /characters

mxzpcg_homepage:
    path:     /
    defaults: { _controller: MXZPCGBundle:Default:index }

