MXZ\PCGBundle\Entity\Characters:
    type: entity
    table: null
    repositoryClass: MXZ\PCGBundle\Entity\CharactersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        race:
            targetEntity: Races
            inversedBy: characters
            joinColumn:
                name: race
                referencedColumnName: id
        STR:
            targetEntity: AbilityScores
            inversedBy: characters
            joinColumn:
                name: STR
                referencedColumnName: id
        DEX:
            targetEntity: AbilityScores
            inversedBy: characters
            joinColumn:
                name: DEX
                referencedColumnName: id
        CON:
            targetEntity: AbilityScores
            inversedBy: characters
            joinColumn:
                name: CON
                referencedColumnName: id
        INTe:
            targetEntity: AbilityScores
            inversedBy: characters
            joinColumn:
                name: INTe
                referencedColumnName: id
        WIS:
            targetEntity: AbilityScores
            inversedBy: characters
            joinColumn:
                name: WIS
                referencedColumnName: id
        CHA:
            targetEntity: AbilityScores
            inversedBy: characters
            joinColumn:
                name: CHA
                referencedColumnName: id
    fields:
        name:
            type: string
            length: 255
        level:
            type: array
            column: level
        alignment:
            type: string
            length: '2'
        size:
            type: string
            length: 255
        hP:
            type: integer
            column: HP
        dR:
            type: string
            length: 255
            column: DR
        initiative:
            type: integer
            column: Initiative
        skills:
            type: array
            column: Skills
        feats:
            type: array
            column: Feats
        specialAbilities:
            type: string
            length: 255
            column: 'Special_Abilities'
        languages:
            type: string
            length: 255
            column: Languages
        xP:
            type: integer
            column: XP
        unspent_levels:
            type: integer
            column: unspent_levels
        unspent_feats:
            type: integer
            column: unspent_feats
        unspent_skills:
            type: integer
            column: unspent_skills
        unspent_as:
            type: integer
            column: unspent_as
        lvl:
            type: integer
            column: total_level
    lifecycleCallbacks: {  }
