<?php

namespace MXZ\PCGBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatsRepository extends EntityRepository
{
}
